### ISSUE TITLE
git ignore issues

### ISSUE THREAD

**Issue by mistkafka** [JolieYang/Out#1]
```
    modified:   Out/Out/Base.lproj/LaunchScreen.storyboard
    modified:   Out/Out/Base.lproj/Main.storyboard
```

you may need add *.storyboard to your git ignore file.

**Comment by JolieYang** [comment]
Why? It's modified,why ignore

**Comment by mistkafka** [comment]
is *.storyboard project build file? The project build file should be ignore. Just like C/C++ program's compile file should be ignore.

**Comment by JolieYang** [comment]
yeah,it's UI file,I change the UI by storyboard
